START_SCREEN_SIZE = (960, 540)
START_SCREEN_WIDTH, START_SCREEN_HEIGHT = START_SCREEN_SIZE

GAME_FIELD_SIZE = START_SCREEN_SIZE
GAME_FIELD_WIDTH, GAME_FIELD_HEIGHT = GAME_FIELD_SIZE

IS_DEBUG = True

PLAYER_SPEED = 10
PLAYER_SPEED_OF_FALLING_COEFFICIENT = 1
PLAYER_JUMP_FORCE = 20
