
GAME_FIELD_SIZE = (960, 540)
GAME_FIELD_PROPORTIONS = 16 / 9

GAME_FIELD_WIDTH, GAME_FIELD_HEIGHT = GAME_FIELD_SIZE

MAIN_WINDOW_SCALE = 0.7

IS_DEBUG = True

PLAYER_SPEED = 10
PLAYER_SPEED_OF_FALLING_COEFFICIENT = 1
PLAYER_JUMP_FORCE = 20
